version: '3.3'

networks:
  db:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data:
  postgres_data:

services:
  api:
    container_name: api
    image: maven:3.8.3-openjdk-17
    working_dir: /home/java/app
    restart: always
    command: ./mvnw spring-boot:run -Dspring-boot.run.jvmArguments="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
    volumes:
      - .././:/home/java/app
    ports:
      - "8085:8085"
      - "5005:5005"
    networks:
      - db
    depends_on:
      - db
  db:
    container_name: db
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - postgres_data:/data/postgres
    ports:
      - "6060:6060"
    networks:
      - db
    restart: unless-stopped
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - db
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    networks:
      - db
